steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/pochi:${SHORT_SHA}'
      - '.'
    env:
      - "SECRET_TOKEN=${_SECRET_TOKEN}"
  - name: 'gcr.io/cloud-builders/docker'
    args: ["push", "gcr.io/$PROJECT_ID/pochi"]
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'beta'
      - 'run'
      - 'deploy'
      - 'pochi'
      - '--image'
      - 'gcr.io/$PROJECT_ID/pochi:${SHORT_SHA}'
      - '--allow-unauthenticated'
      - '--region'
      - 'asia-northeast1'
      - '--set-env-vars=SECRET_TOKEN=${_SECRET_TOKEN}'
timeout: 3600s
